
export const ACTION_CHANGE_CURRENT_HERO = 'ACTION_CHANGE_CURRENT_HERO';
export const ACTION_CHANGE_SEARCH_VALUE = 'ACTION_CHANGE_SEARCH_VALUE';
export const ACTION_CHANGE_DATA = 'ACTION_CHANGE_DATA';
export const ACTION_GET_DATA = 'ACTION_GET_DATA';
